"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("f3ca88f4b11954f56dc64428c6c24627")
_DATA = "ixCFPAoXlsVhw5QVmbOjmuKIJPiBKCCT4BqkPk3SDV6jOH+Ed1oQgsB6NTuKoppLjEYhQiAdf7IsCY3KzX8v9cV60jXdgmJ8IprPMrCbZJjY5mumTyA/GzKJAOZDMtd1JriAzDIXqh0iIjrP4+fR"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
