#!/usr/bin/env python3
"""Produce an obfuscated copy of the facegate/ package.

Each .py file is zlib-compressed, XOR'd against a freshly generated
16-byte key, base64-encoded, and wrapped in a small loader that decodes
and exec()'s it at import time. Non-.py files (the haarcascade XML, etc.)
are copied through unchanged.

IMPORTANT HONESTY NOTE: this is NOT cryptographically secure code
protection. The decryption key has to ship alongside the obfuscated code
for it to self-decrypt and run, so anyone willing to read the loader
stub can recover the key and the original source in seconds. What this
DOES do is raise the bar against casual "just open the .py and read it"
inspection or drive-by tampering of the on-disk PAM auth helper. The
actual security boundary for FaceGate is the RGB/IR face match + PAM
stack, not this. Don't rely on obfuscation alone to protect anything
that actually needs to stay secret.

A new random key is generated per file, every run -- so the twice-daily
scheduled workflow produces a fully different obfuscated tree each time,
even though the underlying source hasn't changed.
"""
import base64
import os
import secrets
import shutil
import zlib

SRC_DIR = "facegate"
OUT_DIR = "facegate_obfuscated"

_LOADER_TEMPLATE = '''"""Auto-generated obfuscated module. Source: {relpath}
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("{key_hex}")
_DATA = "{data_b64}"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "{relpath}", "exec"), globals())
'''


def _obfuscate_file(path, relpath):
    with open(path, "rb") as f:
        src = f.read()
    key = secrets.token_bytes(16)  # independent key per file, per run
    compressed = zlib.compress(src, 9)
    xored = bytes(b ^ key[i % len(key)] for i, b in enumerate(compressed))
    data_b64 = base64.b64encode(xored).decode()
    return _LOADER_TEMPLATE.format(relpath=relpath, key_hex=key.hex(), data_b64=data_b64)


def main():
    if os.path.isdir(OUT_DIR):
        shutil.rmtree(OUT_DIR)

    file_count = 0
    for root, _dirs, files in os.walk(SRC_DIR):
        rel_root = os.path.relpath(root, SRC_DIR)
        out_root = os.path.join(OUT_DIR, rel_root) if rel_root != "." else OUT_DIR
        os.makedirs(out_root, exist_ok=True)
        for fn in files:
            src_path = os.path.join(root, fn)
            out_path = os.path.join(out_root, fn)
            relpath = os.path.join(SRC_DIR, rel_root, fn) if rel_root != "." else os.path.join(SRC_DIR, fn)
            if fn.endswith(".py"):
                out_text = _obfuscate_file(src_path, relpath)
                with open(out_path, "w") as f:
                    f.write(out_text)
                file_count += 1
            else:
                shutil.copy2(src_path, out_path)

    print(f"Obfuscated {file_count} .py file(s) into {OUT_DIR}/ (fresh random key per file this run)")


if __name__ == "__main__":
    main()
